project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "House Price Prediction"
  site-url: "https://jonathan-manurung.github.io/Housing-Market-Prediction-musa-550-final" 
  repo-url: https://github.com/jonathan-manurung/Housing-Market-Prediction-musa-550-final 
  repo-actions: [source]

  page-footer:
    right: "&copy; 2023 Jonathan Manurung. Built with [Quarto](https://quarto.org/). "
    
  sidebar:
    logo: "images/Home_Price_Model.png"
    pinned: true
    align: center
    tools:   
      - icon: github
        href: https://github.com/jonathan-manurung/
        text: "MUSA 550 GitHub"
      - icon: envelope-fill
        href: https://mail.google.com/mail/?view=cm&fs=1&to=jonathanhmanurung@gmail.com&su=SUBJECT&body=BODY 
        text: "jonathanhmanurung@gmail.com" 
      - icon: linkedin
        href: https://www.linkedin.com/in/jonathan-harpin-manurung-462a3b117/
        text: "linkedin"

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Fundamentals
      - href: Data Wrangling.ipynb
        text: Data Wrangling
      - text: Analysis
        contents:
          - analysis/Analysis and Result.ipynb
      - href: summary.qmd
        text: Conclusive Overview
      

format:
  html:
    highlight-style: solarized
    theme: litera
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




