---
title: "HOUSING MARKET PREDICTION"
subtitle: "Data-Driven Predictions for Home Prices"
---

## Fundamentals

Predicting house prices is important for real estate company and for potential homebuyers or sellers. For the real estate, house prices prediction can be crucial for inform market analysis, strategies, risk mitigation, and particularly for price competition. Good house price predcition considered to be advantage for the real estate company in competition with the others. Potential homebuyers and sellers are also benefit from the existence of an accurate house price prediction model.it empower potential buyers and sellers to make a data-driven decision, allocate budget effectively, negotiate confidently, and assess potential investment in a property.

Obtaining accurate house price prediction is challenging. There is no such thing as a perfect prediction, but we can make a better prediction for a house price. There are many factors related to house pricing such as internal characteristic from property assessment, public amenities and disamenities nearby, crimes nearby, and market price condition. In this project, we deliver the house price prediction for city of Philadelphia using data from Philadelphia's Open Data portal. This is the most challenging part in this project, to find correlating factors or variables that directly affect the house price in one area.

This website will provide the best overview of the house price prediction process, including the variables used for price-changing factors, the model-building process, and the methods for validating the accuracy of the model


::: {.callout-important}
This prediction model is created to provide house price prediction in city of Philadelphia based on factos such as internal characteristic and public amenities and/or disamenities.
:::





 
